# Generated by Django 5.1.2 on 2024-12-06 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('emblem', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('crest', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('playedGames', models.IntegerField()),
                ('won', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('points', models.IntegerField()),
                ('goalDifference', models.IntegerField()),
                ('league',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='participations',
                                   to='api.league')),
                ('team',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='participations',
                                   to='api.team')),
            ],
            options={
                'unique_together': {('team', 'league')},
            },
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='standings',
                                   to='api.league')),
                ('teams', models.ManyToManyField(
                    related_name='standings', to='api.teamparticipation')),
            ],
        ),
    ]
