# Generated by Django 5.1.2 on 2024-10-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_league_team_standings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standings',
            old_name='teams',
            new_name='team',
        ),
    ]
