# Generated by Django 5.1.2 on 2024-10-18 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_team_standings_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goalDifference',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lost',
        ),
        migrations.RemoveField(
            model_name='team',
            name='playedGames',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
        migrations.RemoveField(
            model_name='team',
            name='won',
        ),
        migrations.CreateModel(
            name='TeamParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('playedGames', models.IntegerField()),
                ('won', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('points', models.IntegerField()),
                ('goalDifference', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='participations', to='api.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='participations', to='api.team')),
            ],
            options={
                'unique_together': {('team', 'league')},
            },
        ),
        migrations.AlterField(
            model_name='standings',
            name='teams',
            field=models.ManyToManyField(
                related_name='standings', to='api.teamparticipation'),
        ),
    ]
