# Generated by Django 5.1.2 on 2024-11-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='sbapi_match_competi_0d17da_idx',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='competition',
            new_name='season',
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season'],
                               name='sbapi_match_season__d292ef_idx'),
        ),
    ]
