# Generated by Django 5.1.2 on 2024-11-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbapi', '0002_remove_match_sbapi_match_competi_0d17da_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defendingevent',
            options={'verbose_name': 'Events - Defending',
                     'verbose_name_plural': 'Events - Defending'},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'verbose_name': 'Match - Formations',
                     'verbose_name_plural': 'Matches - Formations'},
        ),
        migrations.AlterModelOptions(
            name='goalkeeperevent',
            options={'verbose_name': 'Events - Goalkeeper',
                     'verbose_name_plural': 'Events - Goalkeeper '},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match',
                     'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='matchplayer',
            options={'verbose_name': 'Match - Player Information',
                     'verbose_name_plural': 'Matches - Player Information'},
        ),
        migrations.AlterModelOptions(
            name='matchteamstats',
            options={'verbose_name': 'Match - Team Information',
                     'verbose_name_plural': 'Matches - Team Information'},
        ),
        migrations.AlterModelOptions(
            name='passevent',
            options={'verbose_name': 'Events - Passing',
                     'verbose_name_plural': 'Events - Passing'},
        ),
        migrations.AlterModelOptions(
            name='possessionevent',
            options={'verbose_name': 'Events - Possession',
                     'verbose_name_plural': 'Events - Possession'},
        ),
        migrations.AlterModelOptions(
            name='shootingevent',
            options={'verbose_name': 'Events - Shooting',
                     'verbose_name_plural': 'Events - Shooting '},
        ),
        migrations.AlterModelOptions(
            name='summaryevent',
            options={'verbose_name': 'Events - Summary',
                     'verbose_name_plural': 'Events - Summary'},
        ),
        migrations.RemoveIndex(
            model_name='possessionevent',
            name='sbapi_event_foul_co_25c843_idx',
        ),
        migrations.RemoveField(
            model_name='possessionevent',
            name='foul_committed',
        ),
        migrations.RemoveField(
            model_name='possessionevent',
            name='foul_given',
        ),
        migrations.AddField(
            model_name='summaryevent',
            name='foul_committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summaryevent',
            name='foul_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='summaryevent',
            index=models.Index(
                fields=['foul_committed'], name='sbapi_event_foul_co_270625_idx'),
        ),
    ]
