# Generated by Django 5.1.2 on 2024-11-30 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbapi', '0003_alter_defendingevent_options_alter_formation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalkeeperevent',
            options={'verbose_name': 'Events - Goalkeeper',
                     'verbose_name_plural': 'Events - Goalkeeper'},
        ),
    ]
